server:
  port: 8040
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-group-1
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.use.type.headers: false
        spring.json.value.default.type: java.util.HashMap

  mail:
    host: localhost
    port: 1025
    username: louay
    password: louay
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

